import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import adminRouter from "./admin";
import metricsRouter from "./metrics";
import cmsSiteHealthRouter from "./cms/siteHealth";
import cmsPublishBlocksRouter from "./cms/publishBlocks";
import assetsRouter from "./assets";
import eventsRouter from "./events";
import formsRouter from "./forms";
import authRouter from "./auth";
import insightsRouter from "./insights";
import cmsPostsRouter from "./cms/posts";
import cmsTaxonomyRouter from "./cms/taxonomy";
import cmsMediaRouter from "./cms/media";
import cmsAssetCategoriesRouter from "./cms/assetCategories";
import cmsLibraryAssetsRouter from "./cms/libraryAssets";
import cmsCommentsRouter from "./cms/comments";
import cmsUsersRouter from "./cms/users";
import cmsCapabilitiesRouter from "./cms/capabilities";
import cmsAnalyticsRouter from "./cms/analytics";
import cmsTrafficRouter from "./cms/traffic";
import trafficRouter from "./traffic";
import siteSettingsRouter from "./siteSettings";
import servicesRouter from "./services";
import collateralRouter from "./collateral";
import collateralResourcesRouter from "./collateralResources";
import teamMembersRouter from "./teamMembers";
import videosRouter from "./videos";
import whitePapersRouter from "./whitePapers";
import seoRouter from "./seo";
import wixRedirectsRouter from "./wixRedirects";
import notFoundLogsRouter from "./notFoundLogs";
import workshopsRouter from "./workshops";
import polarisRouter from "./polaris";
import caseStudiesRouter from "./caseStudies";
import applicationsRouter from "./applications";
import modelsRouter from "./models";
import aboutContentRouter from "./aboutContent";
import faqRouter from "./faq";
import contentParentPagesRouter from "./contentParentPages";
import entraMappingsRouter from "./entraMappings";
import hubspotAdminRouter from "./hubspotAdmin";
import speAdminRouter from "./speAdmin";
import clientOrgsRouter from "./clientOrgs";
import securityLogRouter from "./cms/securityLog";
import bookingsRouter from "./bookings";
import aiGroundingRouter from "./aiGrounding";
import aiChatRouter from "./aiChat";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(adminRouter);
router.use(metricsRouter);
router.use(cmsSiteHealthRouter);
router.use(cmsPublishBlocksRouter);
router.use(assetsRouter);
router.use(eventsRouter);
router.use(formsRouter);
router.use(authRouter);
router.use(insightsRouter);
router.use(cmsPostsRouter);
router.use(cmsTaxonomyRouter);
router.use(cmsMediaRouter);
router.use(cmsAssetCategoriesRouter);
router.use(cmsLibraryAssetsRouter);
router.use(cmsCommentsRouter);
router.use(cmsUsersRouter);
router.use(cmsCapabilitiesRouter);
router.use(cmsAnalyticsRouter);
router.use(cmsTrafficRouter);
router.use(trafficRouter);
router.use(siteSettingsRouter);
router.use(servicesRouter);
router.use(collateralRouter);
router.use(collateralResourcesRouter);
router.use(teamMembersRouter);
router.use(videosRouter);
router.use(whitePapersRouter);
router.use(seoRouter);
router.use(wixRedirectsRouter);
router.use(notFoundLogsRouter);
router.use(workshopsRouter);
router.use(polarisRouter);
router.use(caseStudiesRouter);
router.use(applicationsRouter);
router.use(modelsRouter);
router.use(aboutContentRouter);
router.use(faqRouter);
router.use(contentParentPagesRouter);
router.use(entraMappingsRouter);
router.use(hubspotAdminRouter);
router.use(speAdminRouter);
router.use(clientOrgsRouter);
router.use(securityLogRouter);
router.use(bookingsRouter);
router.use(aiGroundingRouter);
router.use(aiChatRouter);

export default router;
