import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import adminRouter from "./admin";
import metricsRouter from "./metrics";
import cmsSiteHealthRouter from "./cms/siteHealth";
import cmsPublishBlocksRouter from "./cms/publishBlocks";
import assetsRouter from "./assets";
import eventsRouter from "./events";
import formsRouter from "./forms";
import authRouter from "./auth";
import insightsRouter from "./insights";
import cmsPostsRouter from "./cms/posts";
import cmsTaxonomyRouter from "./cms/taxonomy";
import cmsMediaRouter from "./cms/media";
import cmsAssetCategoriesRouter from "./cms/assetCategories";
import cmsLibraryAssetsRouter from "./cms/libraryAssets";
import cmsCommentsRouter from "./cms/comments";
import cmsUsersRouter from "./cms/users";
import cmsCapabilitiesRouter from "./cms/capabilities";
import cmsAnalyticsRouter from "./cms/analytics";
import cmsTrafficRouter from "./cms/traffic";
import cmsTrafficPropertiesRouter from "./cms/trafficProperties";
import trafficRouter from "./traffic";
import siteSettingsRouter from "./siteSettings";
import servicesRouter from "./services";
import collateralRouter from "./collateral";
import collateralResourcesRouter from "./collateralResources";
import teamMembersRouter from "./teamMembers";
import videosRouter from "./videos";
import whitePapersRouter from "./whitePapers";
import seoRouter from "./seo";
import wixRedirectsRouter from "./wixRedirects";
import shortLinksRouter from "./shortLinks";
import notFoundLogsRouter from "./notFoundLogs";
import workshopsRouter from "./workshops";
import polarisRouter from "./polaris";
import caseStudiesRouter from "./caseStudies";
import applicationsRouter from "./applications";
import modelsRouter from "./models";
import aboutContentRouter from "./aboutContent";
import landingPagesRouter from "./landingPages";
import faqRouter from "./faq";
import contentParentPagesRouter from "./contentParentPages";
import entraMappingsRouter from "./entraMappings";
import hubspotAdminRouter from "./hubspotAdmin";
import hubspotWebhooksRouter from "./hubspotWebhooks";
import speAdminRouter from "./speAdmin";
import clientOrgsRouter from "./clientOrgs";
import auditLogRouter from "./cms/auditLog";
import seoCoverageRouter from "./cms/seoCoverage";
import bookingsRouter from "./bookings";
import cmsOauthClientsRouter from "./cms/oauthClients";
import aiGroundingRouter from "./aiGrounding";
import aiChatRouter from "./aiChat";
import aiAskRouter from "./aiAsk";
import cspRouter from "./csp";
import cspViolationsRouter from "./cms/cspViolations";
import launchReadinessRouter from "./cms/launchReadiness";
import portalRouter from "./portal";
import portalNebulaRouter from "./portalNebula";
import portalOrionRouter from "./portalOrion";
import portalDocumentsAdminRouter from "./portalDocumentsAdmin";
import portalAppsRouter from "./portalApps";
import cmsPortalArtifactsRouter from "./cmsPortalArtifacts";
import ogRouter from "./og";
import careersRouter from "./careers";
import emailWebhookRouter from "./emailWebhook";
import adminEmailRouter from "./adminEmail";
import searchRouter from "./search";
import constellationDemoRouter from "./constellationDemo";
import portalConstellationRouter from "./portalConstellation";
import experimentsRouter from "./experiments";
import adminExperimentsRouter from "./adminExperiments";
import cmsApiKeysRouter from "./cms/apiKeys";
import briefingPodcastRouter from "./briefingPodcast";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(adminRouter);
router.use(metricsRouter);
router.use(cmsSiteHealthRouter);
router.use(cmsPublishBlocksRouter);
router.use(assetsRouter);
router.use(eventsRouter);
router.use(formsRouter);
router.use(authRouter);
router.use(insightsRouter);
router.use(cmsPostsRouter);
router.use(cmsTaxonomyRouter);
router.use(cmsMediaRouter);
router.use(cmsAssetCategoriesRouter);
router.use(cmsLibraryAssetsRouter);
router.use(cmsCommentsRouter);
router.use(cmsUsersRouter);
router.use(cmsCapabilitiesRouter);
router.use(cmsAnalyticsRouter);
router.use(cmsTrafficRouter);
router.use(cmsTrafficPropertiesRouter);
router.use(trafficRouter);
router.use(siteSettingsRouter);
router.use(servicesRouter);
router.use(collateralRouter);
router.use(collateralResourcesRouter);
router.use(teamMembersRouter);
router.use(videosRouter);
router.use(whitePapersRouter);
router.use(seoRouter);
router.use(wixRedirectsRouter);
router.use(shortLinksRouter);
router.use(notFoundLogsRouter);
router.use(workshopsRouter);
router.use(polarisRouter);
router.use(caseStudiesRouter);
router.use(applicationsRouter);
router.use(modelsRouter);
router.use(aboutContentRouter);
router.use(landingPagesRouter);
router.use(faqRouter);
router.use(contentParentPagesRouter);
router.use(entraMappingsRouter);
router.use(hubspotAdminRouter);
router.use(hubspotWebhooksRouter);
router.use(speAdminRouter);
router.use(clientOrgsRouter);
router.use(auditLogRouter);
router.use(seoCoverageRouter);
router.use(bookingsRouter);
router.use(cmsOauthClientsRouter);
router.use(aiGroundingRouter);
router.use(aiChatRouter);
router.use(aiAskRouter);
router.use(cspRouter);
router.use(cspViolationsRouter);
router.use(launchReadinessRouter);
router.use(portalRouter);
router.use(portalNebulaRouter);
router.use(portalOrionRouter);
router.use(portalDocumentsAdminRouter);
router.use(portalAppsRouter);
router.use(cmsPortalArtifactsRouter);
router.use(ogRouter);
router.use(careersRouter);
router.use(emailWebhookRouter);
router.use(adminEmailRouter);
router.use(searchRouter);
router.use(constellationDemoRouter);
router.use(portalConstellationRouter);
router.use(experimentsRouter);
router.use(adminExperimentsRouter);
router.use(cmsApiKeysRouter);
router.use(briefingPodcastRouter);

export default router;
