import { useEffect, useState } from "react";
import { ArrowRight, Sparkles } from "lucide-react";
import { CONSTELLATION_DEMO_SEED_ID } from "@/data/constellation-demo-seed";

const BASE_PATH = (import.meta.env.BASE_URL || "/").replace(/\/$/, "");

interface NarrativeResponse {
  seedId: string;
  generatedAt: string;
  cached: boolean;
  paragraphs: string[];
}

export function DemoNarrative({ onContinue }: { onContinue: () => void }) {
  const [data, setData] = useState<NarrativeResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    const url = `${BASE_PATH}/api/demos/constellation/narrative?seedId=${encodeURIComponent(
      CONSTELLATION_DEMO_SEED_ID,
    )}`;
    fetch(url, { credentials: "include" })
      .then(async (res) => {
        if (!res.ok) throw new Error(`narrative_${res.status}`);
        return (await res.json()) as NarrativeResponse;
      })
      .then((json) => {
        if (!cancelled) setData(json);
      })
      .catch((err) => {
        if (!cancelled) setError(err instanceof Error ? err.message : String(err));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="space-y-6" data-testid="constellation-demo-narrative">
      <header>
        <p className="text-xs uppercase tracking-widest text-primary mb-1 inline-flex items-center gap-2">
          <Sparkles className="h-3.5 w-3.5" /> AI executive narrative
        </p>
        <h3 className="text-2xl md:text-3xl font-bold">Here's what changed this week</h3>
        <p className="text-sm text-muted-foreground mt-1">
          Generated by Constellation from the live engagement data above. Cached so every
          stakeholder sees the same summary.
        </p>
      </header>

      <div className="rounded-2xl border border-border bg-card p-6 md:p-8">
        {!data && !error && (
          <div className="space-y-3" aria-busy="true" aria-label="Generating narrative">
            <div className="h-3 w-3/4 rounded bg-muted animate-pulse" />
            <div className="h-3 w-full rounded bg-muted animate-pulse" />
            <div className="h-3 w-5/6 rounded bg-muted animate-pulse" />
            <div className="h-3 w-2/3 rounded bg-muted animate-pulse" />
          </div>
        )}
        {error && (
          <p className="text-sm text-rose-300">
            We couldn't reach the narrative service in this sandbox. Refresh to try again.
          </p>
        )}
        {data && (
          <div className="space-y-4 text-base md:text-lg leading-relaxed">
            {data.paragraphs.map((p, i) => (
              <p key={i}>{p}</p>
            ))}
            <p className="text-xs text-muted-foreground pt-2">
              {data.cached ? "Served from cache" : "Generated just now"} ·{" "}
              {new Date(data.generatedAt).toLocaleString("en-US", {
                month: "short",
                day: "numeric",
                hour: "numeric",
                minute: "2-digit",
              })}
            </p>
          </div>
        )}
      </div>

      <div className="flex justify-end">
        <button
          type="button"
          onClick={onContinue}
          className="inline-flex h-11 items-center justify-center rounded-md bg-primary px-6 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90"
          data-testid="constellation-demo-narrative-next"
          disabled={!data && !error}
        >
          Drill into the slipping deliverable
          <ArrowRight className="ml-2 h-4 w-4" />
        </button>
      </div>
    </div>
  );
}
