// Microsoft Graph mail helper for the Briefing Podcast inbound flow.
//
// All synozur.com mail runs through Microsoft 365, so clients (and the
// Copilot Worker's own briefing) deliver into a watched shared mailbox. The
// API server subscribes to that mailbox via Graph change notifications;
// when a message arrives Graph POSTs to our webhook, we fetch the body,
// process it, and DELETE the message.
//
// Reuses SpeGraphClient purely for its app-only token acquisition + retry
// wrapper — the Graph credentials (ENTRA_TENANT_ID / ENTRA_APP_CLIENT_ID /
// ENTRA_APP_CLIENT_SECRET) are the same app registration already used for
// SharePoint Embedded. The app needs Mail.ReadWrite (application permission,
// admin-consented) to read and delete from the shared mailbox.
//
// The watched mailbox address is stored in site_settings.briefing_mailbox
// (admin-managed), not in env vars. Webhook URL and clientState are derived
// from SITE_URL and SESSION_SECRET respectively.

import { createHmac } from "crypto";
import {
  SpeGraphClient,
  readSpeGraphConfigFromEnv,
} from "./graphClient";
import { logger } from "../../logger";

const GRAPH_V1_URL = "https://graph.microsoft.com/v1.0";

// Graph caps mail subscriptions at ~4230 minutes (under 3 days). Renew well
// before that.
const SUBSCRIPTION_LIFETIME_MS = 47 * 60 * 60 * 1000; // ~47h

export interface GraphMailConfig {
  mailbox: string; // UPN/email of the watched shared mailbox
  notificationUrl: string; // public https URL of our webhook
  clientState: string; // shared secret echoed in notifications
}

export interface GraphMessageHeader {
  name: string;
  value: string;
}

export interface GraphMessage {
  id: string;
  subject: string;
  bodyHtml: string;
  bodyContentType: string;
  fromAddress: string | null;
  fromName: string | null;
  internetMessageHeaders: GraphMessageHeader[];
}

// Returns true if the message is machine-generated (auto-reply, OOF notice,
// NDR, delivery report, read receipt, etc.) and should always be discarded,
// regardless of whether the sender is on the approved list.
//
// Deliberately does NOT check the subject prefix (Re:/Fw:) because a human
// approved sender may intentionally forward content to the briefing mailbox
// and that should be processed normally.
//
// Checks, in order:
//  1. In-Reply-To     — RFC 2822 header present on all true replies
//  2. Auto-Submitted  — RFC 3834; value other than "no" means auto-generated
//  3. X-Auto-Response-Suppress — Exchange/M365 auto-reply marker
//  4. X-MS-Exchange-Generated-Message-By — server-generated messages
//
// All checks are case-insensitive on both header names and values.
export function isAutoGeneratedEmail(message: GraphMessage): boolean {
  const headers = message.internetMessageHeaders ?? [];
  const headerMap: Record<string, string> = {};
  for (const h of headers) {
    headerMap[h.name.toLowerCase()] = h.value;
  }

  // 1. Reply chain
  if ("in-reply-to" in headerMap) {
    return true;
  }

  // 2. RFC 3834 auto-response (auto-replied, auto-generated, auto-notified …)
  const autoSubmitted = headerMap["auto-submitted"];
  if (autoSubmitted && autoSubmitted.toLowerCase() !== "no") {
    return true;
  }

  // 3. Exchange / M365 auto-reply suppress marker — presence alone is enough
  if ("x-auto-response-suppress" in headerMap) {
    return true;
  }

  // 4. Exchange server-generated message (NDRs, read receipts, OOF notices)
  if ("x-ms-exchange-generated-message-by" in headerMap) {
    return true;
  }

  return false;
}

// Legacy wrapper kept for any callers that relied on the combined check.
// New code should use isAutoGeneratedEmail() directly.
export function isDirectInboundEmail(message: GraphMessage): boolean {
  const subject = message.subject ?? "";
  if (/^\s*(re|fw|fwd)\s*:/i.test(subject)) return false;
  return !isAutoGeneratedEmail(message);
}

export interface GraphSubscription {
  id: string;
  expirationDateTime: string;
  resource: string;
  notificationUrl: string;
}

// Build the Graph subscription config for a given watched mailbox.
//
// Webhook URL resolution order (most-specific wins):
//   1. BRIEFING_WEBHOOK_BASE_URL  — explicit override (e.g. a tunnel or alias)
//   2. First entry in REPLIT_DOMAINS — Replit automatically sets this to the
//      deployment's public domain in production, so the webhook always points
//      at the live server even when SITE_URL still points at Wix / an old host.
//   3. SITE_URL — legacy fallback for non-Replit deploys.
//   4. https://synozur.com — hard-coded last resort.
//
// clientState is an HMAC of a fixed label so it never leaks as a separate
// secret — changing SESSION_SECRET automatically rotates it.
export function buildGraphMailConfig(mailbox: string): GraphMailConfig {
  const explicitBase = process.env["BRIEFING_WEBHOOK_BASE_URL"];
  const replitDomain = (process.env["REPLIT_DOMAINS"] ?? "")
    .split(",")
    .map((d) => d.trim())
    .filter(Boolean)[0];
  const siteUrl = (
    explicitBase ??
    (replitDomain ? `https://${replitDomain}` : null) ??
    process.env["SITE_URL"] ??
    "https://synozur.com"
  ).replace(/\/$/, "");
  const secret = process.env["SESSION_SECRET"] ?? "dev-secret";
  const clientState = createHmac("sha256", secret)
    .update("briefing-subscription-v1")
    .digest("hex")
    .slice(0, 64);
  return {
    mailbox,
    notificationUrl: `${siteUrl}/api/briefing-podcast/webhook`,
    clientState,
  };
}

export class GraphMailClient {
  private readonly graph: SpeGraphClient;

  constructor() {
    const cfg = readSpeGraphConfigFromEnv();
    if (!cfg) {
      throw new Error(
        "Graph mail client requires ENTRA_TENANT_ID / ENTRA_APP_CLIENT_ID / ENTRA_APP_CLIENT_SECRET",
      );
    }
    this.graph = new SpeGraphClient(cfg);
  }

  private mailboxResource(mailbox: string): string {
    return `/users/${encodeURIComponent(mailbox)}/mailFolders('inbox')/messages`;
  }

  async createSubscription(cfg: GraphMailConfig): Promise<GraphSubscription> {
    const expiration = new Date(
      Date.now() + SUBSCRIPTION_LIFETIME_MS,
    ).toISOString();
    const body = {
      changeType: "created",
      notificationUrl: cfg.notificationUrl,
      resource: this.mailboxResource(cfg.mailbox),
      expirationDateTime: expiration,
      clientState: cfg.clientState,
    };
    const sub = await this.graph.request<GraphSubscription>(
      `${GRAPH_V1_URL}/subscriptions`,
      {
        method: "POST",
        body: JSON.stringify(body),
        headers: { "Content-Type": "application/json" },
      },
    );
    logger.info(
      { subscriptionId: sub.id, expiration: sub.expirationDateTime },
      "Created Graph mail subscription for briefing mailbox",
    );
    return sub;
  }

  async renewSubscription(subscriptionId: string): Promise<GraphSubscription> {
    const expiration = new Date(
      Date.now() + SUBSCRIPTION_LIFETIME_MS,
    ).toISOString();
    return this.graph.request<GraphSubscription>(
      `${GRAPH_V1_URL}/subscriptions/${subscriptionId}`,
      {
        method: "PATCH",
        body: JSON.stringify({ expirationDateTime: expiration }),
        headers: { "Content-Type": "application/json" },
      },
    );
  }

  async listSubscriptions(): Promise<GraphSubscription[]> {
    const data = await this.graph.request<{ value: GraphSubscription[] }>(
      `${GRAPH_V1_URL}/subscriptions`,
    );
    return data.value ?? [];
  }

  async deleteSubscription(subscriptionId: string): Promise<void> {
    await this.graph.request<void>(
      `${GRAPH_V1_URL}/subscriptions/${subscriptionId}`,
      { method: "DELETE" },
    );
  }

  // Fetch a single message's body + sender + internet headers.
  // `mailbox` is the watched shared mailbox; `messageId` comes from the
  // change notification. `internetMessageHeaders` is included so callers
  // can detect replies, forwards, and auto-replies before processing.
  async getMessage(mailbox: string, messageId: string): Promise<GraphMessage> {
    const url =
      `${GRAPH_V1_URL}/users/${encodeURIComponent(mailbox)}/messages/${messageId}` +
      `?$select=id,subject,body,from,internetMessageHeaders`;
    const raw = await this.graph.request<{
      id: string;
      subject?: string;
      body?: { contentType?: string; content?: string };
      from?: { emailAddress?: { address?: string; name?: string } };
      internetMessageHeaders?: Array<{ name: string; value: string }>;
    }>(url);
    return {
      id: raw.id,
      subject: raw.subject ?? "(no subject)",
      bodyHtml: raw.body?.content ?? "",
      bodyContentType: raw.body?.contentType ?? "html",
      fromAddress: raw.from?.emailAddress?.address?.toLowerCase() ?? null,
      fromName: raw.from?.emailAddress?.name ?? null,
      internetMessageHeaders: raw.internetMessageHeaders ?? [],
    };
  }

  async deleteMessage(mailbox: string, messageId: string): Promise<void> {
    await this.graph.request<void>(
      `${GRAPH_V1_URL}/users/${encodeURIComponent(mailbox)}/messages/${messageId}`,
      { method: "DELETE" },
    );
  }
}
